# DF Filtering and Reduction

This notebook aims to effectively adjust the output after the completed BLASTp. The columns that are to be kept, are the TCID, Query ID, Mechanism from TCDB, and R:Reaction, E-value and Identity.

In [1]:
import pandas as pd

In [15]:
cols_to_load = [1, 2, 9, 11, 14, 15, 23]
proteins = pd.read_csv("identified_proteins.tsv", sep="\t", usecols=cols_to_load, dtype=str)
proteins.drop_duplicates(inplace=True)
proteins.rename(columns={"Reaction":"TCDB:Reaction", "R:Equation":"Rhea:Reaction"}, inplace=True)
new_order = ["UID", "TCID", "QueryID", "TCDB:Reaction", "Rhea:Reaction", "Evalue", "Identity"]
proteins = proteins[new_order]
proteins

,UID,TCID,QueryID,TCDB:Reaction,Rhea:Reaction,Evalue,Identity
0,A0JCJ5,1.B.1.1.7,sp|P06996|OMPC_ECOLI,molecule (out) ⇌ molecule (in),NaN,5.04e-06,35.878
1,A0JCJ5,1.B.1.1.7,sp|P76335|YEDS_ECOLI,molecule (out) ⇌ molecule (in),NaN,1.9e-08,38.686
2,A0L4L0,3.A.1.132.3,sp|P0AEZ3|MIND_ECOLI,Solute (in) + ATP → Solute (out) + ADP + Pi,NaN,8.54e-06,43.396
3,A0L4L0,3.A.1.132.3,sp|P0AF08|APBC_ECOLI,Solute (in) + ATP → Solute (out) + ADP + Pi,NaN,7.69e-70,39.368
4,A0L4L0,3.A.1.132.3,sp|P0AEZ3|MIND_ECOLI,Substrate (out) + ATP → Substrate (in) + ADP + Pi,NaN,8.54e-06,43.396
...,...,...,...,...,...,...,...
193911,VZT40043.1,4.A.2.1.28,sp|P0A9N0|PTSO_ECOLI,NaN,NaN,3.28e-16,48.276
193912,MFA7902620.1,4.A.2.1.28,sp|P69820|ULAC_ECOLI,NaN,NaN,7.96e-06,31.461
193913,MFA7902620.1,4.A.2.1.28,sp|P69829|PTSN_ECOLI,NaN,NaN,3.19e-36,47.02
193914,MFA7902620.1,4.A.2.1.28,sp|P69811|PTFAH_ECOLI,NaN,NaN,1.35e-06,30.075
193915,WRI60233.1,3.D.4.11.2,sp|P0ABI8|CYOB_ECOLI,NaN,NaN,5.32e-92,36.242

In [18]:
missing_reactions = proteins[proteins["TCDB:Reaction"].isna() & proteins["Rhea:Reaction"].isna()]
missing_reactions

,UID,TCID,QueryID,TCDB:Reaction,Rhea:Reaction,Evalue,Identity
6,A0M015,1.A.62.2.1,sp|P0AGM2|YICG_ECOLI,NaN,NaN,5.61e-46,39.394
7,A0M015,1.A.62.2.1,sp|P0AFP0|YADS_ECOLI,NaN,NaN,6.96e-43,37.436
369,A0QQH3,2.A.4.1.5,sp|P75757|ZITB_ECOLI,NaN,NaN,1.17e-38,36.12
386,A1EMW4,3.A.11.2.3,sp|P0AAR8|YBAV_ECOLI,NaN,NaN,4.85e-18,50.588
459,A1S5F2,2.A.2.3.6,sp|P0CE44|UIDB_ECOLI,NaN,NaN,2.2299999999999997e-52,30.735
...,...,...,...,...,...,...,...
193911,VZT40043.1,4.A.2.1.28,sp|P0A9N0|PTSO_ECOLI,NaN,NaN,3.28e-16,48.276
193912,MFA7902620.1,4.A.2.1.28,sp|P69820|ULAC_ECOLI,NaN,NaN,7.96e-06,31.461
193913,MFA7902620.1,4.A.2.1.28,sp|P69829|PTSN_ECOLI,NaN,NaN,3.19e-36,47.02
193914,MFA7902620.1,4.A.2.1.28,sp|P69811|PTFAH_ECOLI,NaN,NaN,1.35e-06,30.075
193915,WRI60233.1,3.D.4.11.2,sp|P0ABI8|CYOB_ECOLI,NaN,NaN,5.32e-92,36.242